### ISSUE TITLE
feature request: stup option

### ISSUE THREAD

**Issue by doodzik** [tomterl/metalsmith-convert#11]
I would love to have something like a stup option. 
So that the files are just renamed without transforming them.
This would increase the building process in development.

**Comment by tomterl** [comment]
Hmm - metalsmith works by having an array with the files contents in memory, so I don't know how much of a speed-up we can achieve by omitting the actual conversion step, but I'll see what I can do.

**Comment by doodzik** [comment]
Oh yeah. I didn't think about that. I'm not 100% sure about that thought, because the contents field of a file is a Buffer object and objects are passed by reference in js.
So something like this shouldn't allocate new memory:
```js
files[newFilename].contents = files[originalFilename].contents
```
or even this:
```js
files[newFilename] = files[originalFilename]
```
I open a pr.
