### ISSUE TITLE
outputting multiple sizes in pipeline doesn't work

### ISSUE THREAD

**Issue by jvolker** [tomterl/metalsmith-convert#13]
Doing the following only serves me the first file size, but not the second:

```
.use(convert(
    {
    "src": "**/*.jpg",
    "target": "jpg",
    "resize": {width: 3200, height: 2000, resizeStyle: 'aspectfit'},
    "nameFormat": "%b_max%e"
  },
  {
    "src": "**/*.jpg",
    "target": "jpg",
    "resize": {width: 320, height: 240, resizeStyle: 'aspectfit'},
    "nameFormat": "%b_thumb%e"
  }))
```

Is there a way to configure it to create 2 different file sizes?

Thanks!

**Comment by tomterl** [comment]
You have to pass a list of configurations, so make that 

    use(convert([
        {
        "src": "**/*.jpg",
        "target": "jpg",
        "resize": {width: 3200, height: 2000, resizeStyle: 'aspectfit'},
        "nameFormat": "%b_max%e"
      },
      {
        "src": "**/*.jpg",
        "target": "jpg",
        "resize": {width: 320, height: 240, resizeStyle: 'aspectfit'},
        "nameFormat": "%b_thumb%e"
      }]))

**Comment by jvolker** [comment]
Oh … ;)

Thanks for the quick help!
