### ISSUE TITLE
keeping original file name with remove option removes converted file

### ISSUE THREAD

**Issue by jvolker** [tomterl/metalsmith-convert#15]
Keeping the original filename and removing the original source file don't play well together. 

```
"nameFormat": "%b%e",
"remove": true
```

This removes the converted file, which is confusing and not what the documentation describes. Only the source file should be removed.
Of course there can't be two files with the same name. So maybe in that case the source file should get a suffix like `_source` or `_org`?

**Comment by tomterl** [comment]
Well, it doesn't make much sense to do that -- it's a bit like complaining that it it hurts if you stick your finger in your eye -- just don't do it ;-)

I'll have look at it, but possibly I just forbid to use %b%e -- what is your use case, why do you convert the files to something you don't want to see reflected in the filename?

**Comment by tomterl** [comment]
Or we ignore 'remove' if nameFormat is %b%e, as it is unnecessary in that case

**Comment by jvolker** [comment]
What happend to me: I was just playing around and decided I didn't want the source files (used `remove`). Later I decided I wanted to keep the (well picked) file names (used `%b%e`). And was then wondering why I ended up with no files at all. 
I think at least the documentation should give a heads up!

> Or we ignore 'remove' if nameFormat is %b%e, as it is unnecessary in that case 

I like this idea even better. Though I can imagine somebody would like to rename the source instead of the target. So I suggest to rename the source in this case, as just ignoring would basically be the same as using `%b%e` without `remove`.

The files I'm converting need to keep their file names, as their name describes their purpose and are accessed like that directly in the HTML (e.g. projects fullscreen header images or projects thumbnails used in an image grid). Honestly I see no reason why I should expose conversion details or add anything else to the filename. It's just not necessary. They should only be downsized, nothing else. Hope this explains it enough. 

In the end, it might be just my opinion to my specific use case.
Thanks for considering it!

**Comment by tomterl** [comment]
0.3.5 will fix this behaviour by ignoring 'remove' if the format is '%b%e' (this is an implementation detail, it does not need to be mentioned in the readme, the deletion was a bug); additionally there is a new option 'renameSourceFormat', that is used as 'nameFormat' is, and renames the source-file.

Let me know what you think -- if the current master state covers #14 and and #15 for you, I tag and push 0.3.5 tonight or tomorrow (MET).

**Comment by jvolker** [comment]
Yes, that's really helpful! It works great. Thanks so much!
