### ISSUE TITLE
Failed at the imagemagick-native@1.9.3 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by edwardessing** [tomterl/metalsmith-convert#16]
Hey I'm getting the following error when I try installing this package:

`fatal error: too many errors emitted, stopping now [-ferror-limit=]`
`20 errors generated.`
`make: *** [Release/obj.target/imagemagick/src/imagemagick.o] Error 1`
`gyp ERR! build error`
`gyp ERR! stack Error: make failed with exit code: 2`
`gyp ERR! stack     at ChildProcess.onExit`
`(/Users/edward/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)`
`gyp ERR! stack     at emitTwo (events.js:88:13)`
`gyp ERR! stack     at ChildProcess.emit (events.js:173:7)`
`gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:201:12)`
`gyp ERR! System Darwin 16.1.0`
`gyp ERR! command "/Users/edward/.nvm/versions/node/v5.2.0/bin/node"`
`"/Users/edward/.nvm/versions/node/v5.2.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"`
`gyp ERR! cwd /Users/edward/Sites/art/node_modules/imagemagick-native`
`gyp ERR! node -v v5.2.0`
`gyp ERR! node-gyp -v v3.3.1`
`gyp ERR! not ok`
`art@1.0.0 /Users/edward/Sites/art
└── node-sass@4.2.0`
`npm WARN art@1.0.0 No repository field.`
`npm ERR! Darwin 16.1.0`
`npm ERR! argv "/Users/edward/.nvm/versions/node/v5.2.0/bin/node"`
`"/Users/edward/.nvm/versions/node/v5.2.0/bin/npm" "install" "--save" "metalsmith-convert"`
`npm ERR! node v5.2.0`
`npm ERR! npm  v3.8.7`
`npm ERR! code ELIFECYCLE`
`npm ERR! imagemagick-native@1.9.3 install: node-gyp rebuild`
`npm ERR! Exit status 1`
`npm ERR!`
**`npm ERR! Failed at the imagemagick-native@1.9.3 install script 'node-gyp rebuild'.`**

p.s. I have installed imagemagick 7.0.4-6 via brew...

any help would be appreciated, thank you!

**Comment by tomterl** [comment]
I'm sorry, I don't have a Mac at hand to investigate; did you search for node-gyp, Mac OS related Bugs in building imagemagick-native, as the error occurs there?

**Comment by tomterl** [comment]
Does brew install the development files (header etc.) needed to build the module?

**Comment by tomterl** [comment]
And did you install pkgconfig, as mentioned in imagemick-natives readme?

**Comment by edwardessing** [comment]
Yep, installed both the pkgconfig and natives packages...

**Comment by tomterl** [comment]
That's too bad, these were the first OS X related problems/solutions I found, would have been nice...

**Comment by tomterl** [comment]
Okay, I found this desperate sounding solution:

> Thanks @bnoordhuis! I had the same issue with no spaces in my file path. Deleting the original 
> node_modules folder from my project, then deleting .node-gyp (I did not have .npmrc), restarting, and
> installing node in my project again with (sudo npm install) worked with no errors.
> 
> Node v5.2.0

In this node-gyp issue: https://github.com/nodejs/node-gyp/issues/809

**Comment by edwardessing** [comment]
Did all of the above and still getting the same issue... ):

**Comment by tomterl** [comment]
imagemick-natives travis-tests pass for node 4.2, is it possible for you to go back to node 4.2 to test this possibility? Or, as a first step, install an imagemagick version < 7.0 via brew to check if there's a problem there? Otherwise maybe open an issue directly at node-imagemagick-native with the full error message you get.

**Comment by tomterl** [comment]
Any progress?

**Comment by edwardessing** [comment]
Sadly no. I tried doing everything you said (with the exception of opening an issue at node-imagemagick-native)...

**Comment by tomterl** [comment]
Solved, see issue 160 in elad/node-imagemagick-native; pkg-config misconfiguration.
