### ISSUE TITLE
Update package.json to latest node-imagemagick

### ISSUE THREAD

**Issue by doup** [tomterl/metalsmith-convert#6]
Right now this doesn't work on io.js. This should be fixed once [the new version](https://github.com/mash/node-imagemagick-native/issues/88) of `node-imagemagick` is published (1.7.0 >) and the `package.json` of `metalsmith-convert` is updated.

**Comment by doup** [comment]
Uhmm… too fast. It seems that still it's not fixed in `node-imagemagick`.

**Comment by tomterl** [comment]
I don't use io.js -- just get  back to me when the changes are sufficientlz solving your problem and I update the package.json, shouldn't be a problem for anyone, as the latest 1.X release will be installed anyhow ATM (^ and not ~ for that reason).

**Comment by tomterl** [comment]
Please re-open if there is an actual issue -- closing for now.
