### ISSUE TITLE
Imagemagick Native version fails under modern nodejs

### ISSUE THREAD

**Issue by ajfisher** [tomterl/metalsmith-convert#8]
Installing this package from npm no longer works if you're using a more recent version of nodejs (v4.x or v5.x) this is due to a current failure in NaN. There is a patch involved but it means working with a specific branch of imagemacgick-native and using that as the dependency.

See this comment here for more information. https://github.com/elad/node-imagemagick-native/pull/102#issuecomment-168004384

Doing a clone of metalsmith-convert, changing the install location to this branch `elad/node-imagemagick-native.git#travis-4.1` and then installing locally into my project allows me to use metalsmith-convert absolutely as normal.

Happy to submit a PR if you want however wasn't certain of how to run the tests etc to package it all up properly to validate nothing else has broken as a result of the upgrade.

**Comment by tomterl** [comment]
I'll gladly accept a PR -- just change what you deem necessary, testing is done automatically.

**Comment by ajfisher** [comment]
Okay cool - will sort that out today

**Comment by tomterl** [comment]
I just added node 4.0 and 4.1 to the travis test setup -- unfortunately image-magick does not compile there, so automatic tests can't work.

**Comment by tomterl** [comment]
Once the release version of imagemagick-native compiles clean against a node >= 4.x, the package.json should b changed again.
