### ISSUE TITLE
performance

### ISSUE THREAD

**Issue by ainthek** [tomterl/metalsmith-convert#9]
Please, Have you any benchmart for converting 100 images ? 

   .use(convert({
        src: '**/*.jpg',
        target: 'png'
    }))

seems unusable to me and seems to block whole build process for minutes

**Comment by doodzik** [comment]
I think this issue has more to do with node-imagemagick-native. Can you check if it is as slow for you as this library is?

**Comment by tomterl** [comment]
Please see if @doodzik s `rename_only` change helps you to speed up your development cycles; If you need a release to do so, please be patient, it follows later today.

**Comment by tomterl** [comment]
Just tagged and published 0.3.4
